import mongoose from "mongoose";
const orderItemSchema = new mongoose.Schema({
  product:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Product",
    required:true
  },
  productName:{
    type:String,
    required:true
  },
  productImage:{
    type:String,
    default:""
  },
  price:{
    type:Number,
    required:true
  },
  quantity:{
    type:Number,
    required:true,
    min:1
  },
  size:{
    type:String,
    default:""
  },
  color:{
    type:String,
    default:""
  },
  subtotal:{
    type:Number,
    required:true
  },
  status:{
    type:String,
    enum:["pending","shipped","out_for_delivery","delivered","cancelled","cancellation_requested","return_requested","returned","return_rejected"],
    default:"pending"
  },
  cancellationReason:{
    type:String,
    default:""
  },
  cancellationRejected:{
    type:Boolean,
    default:false
  },
  returnReason:{
    type:String,
    default:""
  },
  refundAmount:{
    type:Number,
    default:0
  },
  refundedAt:{
    type:Date,
    default:null
  },
  stockRestored:{
    type:Boolean,
    default:false
  },
  restockVerifiedAt:{
    type:Date,
    default:null
  }
},{_id:false})
const addressSchema = new mongoose.Schema({
  addressType:{
    type:String,
    required:true
  },
  fullName:{
    type:String,
    required:true,
    trim:true
  },
  mobile:{
    type:String,
    required:true,
  },
  street:{
    type:String,
    required:true
  },
  city:{
    type:String,
    required:true
  },
  state:{
    type:String,
    required:true
  },
  pincode:{
    type:String,
    required:true
  }
},{_id:false})
const orderSchema = new mongoose.Schema({
  orderId:{
    type:String,
    unique:true,
    required:true
  },
  user:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    required:true
  },
  address: {
    type: Object,
    required: true
  },
  items:{
    type:[orderItemSchema],
    default:[]
  },
  paymentMethod:{
    type:String,
    enum:["COD","RAZORPAY","WALLET"],
    default:"COD"
  },
  paymentStatus:{
    type:String,
    enum:["pending","paid","failed"],
    default:"pending"
  },
  razorpay:{
    orderId:{
      type:String,
      default:""
    },
    paymentId:{
      type:String,
      default:""
    },
    signature:{
      type:String,
      default:""
    },
    paidAt:{
      type:Date,
      default:null
    }
  },
  walletAmountUsed:{
    type:Number,
    default:0
  },
  refundStatus:{
    type:String,
    enum:["none","pending","refunded","rejected"]
  },
  subtotal:{
    type:Number,
    required:true,
    default:0
  },
  discount:{
    type:Number,
    default:0
  },
  coupon: {
    code: { type: String, default: "" },
    discount: { type: Number, default: 0 }
  },
  referralOffer:{
    code:{ type:String, default:"" },
    discount:{ type:Number, default:0 }
  },
  tax:{
    type:Number,
    default:0
  },
  shippingCharge:{
    type:Number,
    default:0
  },
  grandTotal:{
    type:Number,
    required:true,
    default:0
  },
  status:{
    type:String,
    enum:["pending","shipped","out_for_delivery","delivered","cancelled","partially_cancelled","cancellation_requested","return_requested","returned","return_rejected"],
    default:"pending"
  },
  cancellationReason:{
    type:String,
    default:""
  }
},{timestamps:true})

orderSchema.index({user:1});
orderSchema.index({createdAt:-1});
orderSchema.index({status:1});

const Order = mongoose.model("Order", orderSchema);

export default Order;
